require './raskell'
require './apps/double_check/double_check'
require './test/raskell/array'
require './test/raskell/identity'
require './test/raskell/integer'
require './test/raskell/object'
require './test/raskell/proc'
require './test/raskell/core'

require './test/raskell/folds'
#load 'test/raskell/streams'
require './test/raskell/f'
