require './raskell'
require './apps/double_check/double_check'
require_relative './raskell/array'
require_relative './raskell/identity'
require_relative './raskell/integer'
require_relative './raskell/object'
require_relative './raskell/proc'
require_relative './raskell/core'

require_relative './raskell/folds'
#load 'test/raskell/streams'
require_relative './raskell/f'
