require_relative './raskell/nothing'
require_relative './raskell/identity'
require_relative './raskell/integer'
require_relative './raskell/object'
require_relative './raskell/streams'
require_relative './raskell/proc'
require_relative './raskell/array'
require_relative './raskell/folds'
require_relative './raskell/f'
require_relative './version'

